import hmac
import json
import secrets
from pathlib import Path

from aiosmtpd.smtp import AuthResult, LoginPassword

from smtpweb.password_hashing import hash_password, verify_password


class Authenticator:
    """Validates AUTH LOGIN/PLAIN credentials against a single configured
    username + PBKDF2 password hash, using constant-time comparison. The
    password itself is never held anywhere but the client's submission —
    see password_hashing.py."""

    def __init__(self, username: str, password_record: dict):
        self._username = username.encode("utf-8")
        self._password_record = password_record

    def __call__(self, server, session, envelope, mechanism, auth_data):
        if mechanism not in ("LOGIN", "PLAIN") or not isinstance(auth_data, LoginPassword):
            return AuthResult(success=False, handled=False)
        login_ok = hmac.compare_digest(auth_data.login, self._username)
        try:
            submitted = auth_data.password.decode("utf-8")
            password_ok = verify_password(submitted, self._password_record)
        except (UnicodeDecodeError, KeyError, ValueError):
            password_ok = False
        if login_ok and password_ok:
            return AuthResult(success=True)
        return AuthResult(success=False, handled=False)


def resolve_credentials(
    creds_path: Path,
    env_username: str | None,
    env_password: str | None,
    env_var_names: tuple[str, str],
    default_username: str,
) -> tuple[str, dict, bool, str | None]:
    """Return (username, password_record, generated, new_plaintext_password).

    password_record is a PBKDF2 hash record (see password_hashing.py) —
    never plaintext. new_plaintext_password is set only the one time a
    password is freshly generated by this call, since that's the only
    chance to ever see it again; the caller should log/print it
    immediately. generated is True whenever the credential isn't coming
    directly from the two env vars (i.e. it was loaded from, or just
    written to, creds_path)."""
    env_username_name, env_password_name = env_var_names
    if env_username and env_password:
        record = {"username": env_username, **hash_password(env_password)}
        return env_username, record, False, None
    if env_username or env_password:
        raise RuntimeError(
            f"Set both {env_username_name} and {env_password_name}, or neither "
            "(to auto-generate credentials)."
        )

    if creds_path.exists():
        record = json.loads(creds_path.read_text())
        return record["username"], record, True, None

    username = default_username
    password = secrets.token_urlsafe(24)
    record = {"username": username, **hash_password(password)}
    creds_path.parent.mkdir(parents=True, exist_ok=True)
    creds_path.write_text(json.dumps(record, indent=2))
    creds_path.chmod(0o600)
    return username, record, True, password
